spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ai_chat}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        enabled: false
      image:
        enabled: false
      audio:
        transcription:
          enabled: false
        speech:
          enabled: false
      moderations:
        enabled: false
      embedding:
        enabled: false
