-- =================================================================
-- Spring AI Chat 项目 数据库初始化脚本（H2, PostgreSQL兼容模式）
-- 仅用于本地/沙箱快速启动，避免真实PostgreSQL依赖
-- =================================================================

-- 1) 基础表（使用H2语法）
create table if not exists users (
  id           bigint generated by default as identity primary key,
  username     varchar(50) unique not null,
  nickname     varchar(100),
  created_at   timestamp default CURRENT_TIMESTAMP(),
  updated_at   timestamp default CURRENT_TIMESTAMP()
);

create table if not exists conversations (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null,
  title        varchar(200),
  created_at   timestamp default CURRENT_TIMESTAMP(),
  updated_at   timestamp default CURRENT_TIMESTAMP()
);

create table if not exists messages (
  id               bigint generated by default as identity primary key,
  conversation_id  bigint not null,
  role             varchar(20) not null,
  content          text not null,
  thinking         text,
  created_at       timestamp default CURRENT_TIMESTAMP(),
  updated_at       timestamp default CURRENT_TIMESTAMP()
);

create table if not exists message_tool_results (
  id            bigint generated by default as identity primary key,
  message_id    bigint not null,
  tool_name     varchar(50) not null,
  call_sequence int not null,
  tool_input    text,
  tool_result   text,
  status        varchar(20) not null default 'IN_PROGRESS',
  error_message text,
  created_at    timestamp default CURRENT_TIMESTAMP(),
  updated_at    timestamp default CURRENT_TIMESTAMP()
);

-- 2) 索引
create index if not exists idx_conversations_user_id on conversations (user_id);
create index if not exists idx_messages_conversation_id on messages (conversation_id);
create index if not exists idx_message_tool_results_message_id on message_tool_results (message_id);
create index if not exists idx_message_tool_results_message_id_tool_name on message_tool_results (message_id, tool_name);
create index if not exists idx_message_tool_results_message_id_sequence on message_tool_results (message_id, call_sequence);

-- 3) 初始数据（H2使用MERGE实现幂等）
merge into users (username, nickname, created_at, updated_at) key(username)
  values ('admin', '管理员', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
merge into users (username, nickname, created_at, updated_at) key(username)
  values ('test',  '测试用户', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
merge into users (username, nickname, created_at, updated_at) key(username)
  values ('demo',  '演示用户', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
