-- H2-friendly init script for development

create table if not exists users (
  id            bigint generated by default as identity primary key,
  username      varchar(50) unique not null,
  nickname      varchar(100),
  created_at    timestamp default CURRENT_TIMESTAMP,
  updated_at    timestamp default CURRENT_TIMESTAMP
);

create table if not exists conversations (
  id            bigint generated by default as identity primary key,
  user_id       bigint not null,
  title         varchar(200),
  created_at    timestamp default CURRENT_TIMESTAMP,
  updated_at    timestamp default CURRENT_TIMESTAMP
);

create table if not exists messages (
  id               bigint generated by default as identity primary key,
  conversation_id  bigint not null,
  role             varchar(20) not null,
  content          clob not null,
  thinking         clob,
  created_at       timestamp default CURRENT_TIMESTAMP,
  updated_at       timestamp default CURRENT_TIMESTAMP
);

create table if not exists message_tool_results (
  id            bigint generated by default as identity primary key,
  message_id    bigint not null,
  tool_name     varchar(50) not null,
  call_sequence int not null,
  tool_input    clob,
  tool_result   clob,
  status        varchar(20) not null default 'IN_PROGRESS',
  error_message clob,
  created_at    timestamp default CURRENT_TIMESTAMP,
  updated_at    timestamp default CURRENT_TIMESTAMP
);

create index if not exists idx_conversations_user_id on conversations (user_id);
create index if not exists idx_messages_conversation_id on messages (conversation_id);
create index if not exists idx_message_tool_results_message_id on message_tool_results (message_id);
create index if not exists idx_message_tool_results_message_id_tool_name on message_tool_results (message_id, tool_name);
create index if not exists idx_message_tool_results_message_id_sequence on message_tool_results (message_id, call_sequence);

-- Upsert seed users with MERGE (H2 syntax)
merge into users (username, nickname) key(username) values ('admin','管理员');
merge into users (username, nickname) key(username) values ('test','测试用户');
merge into users (username, nickname) key(username) values ('demo','演示用户');

